default:
    @just --list

run:
    go run ./cmd/server

build:
    go build -o server ./cmd/server

tidy:
    go mod tidy

fmt:
    gofmt -w cmd internal

vet:
    go vet ./...

test:
    go test ./...

docker-build:
    docker build -t ai-of-cursor-go-server:latest .

docker-up:
    docker compose up -d --build

docker-down:
    docker compose down

docker-logs:
    docker compose logs -f go-server

test-api:
    ./scripts/test-endpoints.sh

test-api-docker:
    BASE_URL=http://127.0.0.1:8080 ./scripts/test-endpoints.sh
