default:
    @just --list

run:
    go run ./cmd/server

build:
    go build -o server ./cmd/server

tidy:
    go mod tidy

fmt:
    gofmt -w cmd internal

vet:
    go vet ./...

test:
    go test ./...
